= Command Line Interface
:url-sdkman: https://sdkman.io
:url-chocolatey: https://chocolatey.org
:url-sdkman: https://sdkman.io

There are two basic ways to make AsciidoctorJ available as a command line tool.

* Manual installation using the binary distribution.
* Automatic installation using a package manager like {url-sdkman}[SDKMAN^] or {url-chocolatey}[Chocolately^].

== Manual distribution installation

If you download from a xref:distribution.adoc[distribution] (zip or tar), you can get started straight away from the command line.

First, extract the downloaded file.
That puts everything in directory `asciidoctorj-{artifact-version}`.
Within that directory are the `bin` and `lib` directories.

* `bin` contains the executables -- `asciidoctorj` for Linux and macOS, and `asciidoctorj.bat` for Windows.
* `lib` contains the supporting libraries.

Verify the application runs by specifying the appropriate executable with no parameters;
it should display the various run options available (i.e., help).

[source]
[subs="specialcharacters,attributes,callouts"]
----
Linux: asciidoctorj-{artifact-version}/bin/asciidoctorj
Windows: asciidoctorj-{artifact-version}\bin\asciidoctorj.bat
----

Next, say you want to convert an ASCIIDOC (.adoc) file to a pdf.

[source]
[subs="specialcharacters,attributes,callouts"]
----
Linux: asciidoctorj-{artifact-version}/bin/asciidoctorj -b pdf README.adoc
Windows: asciidoctorj-{artifact-version}\bin\asciidoctorj.bat -b pdf README.adoc
----

Boom! That should convert the README to a PDF named README.pdf.
To create a PDF with a different name -- say, READTHIS.pdf -- just add the -o switch:

[source]
[subs="specialcharacters,attributes,callouts"]
----
Linux: asciidoctorj-{artifact-version}/bin/asciidoctorj -b pdf -o READTHIS.pdf README.adoc
Windows: asciidoctorj-{artifact-version}\bin\asciidoctorj.bat -b pdf -o READTHIS.pdf README.adoc
----

== Linux and MacOS installation

A {url-sdkman}[SDKMAN!] candidate is available for easy installation in Linux and MacOS.
This will install the binary distribution and setup the PATH automatically.

 $ sdk install asciidoctorj
 $ asciidoctorj -b pdf README.adoc

== Windows installation

A {url-chocolatey}[Chocolatey] package is available which installs the
asciidoctorj-{artifact-version}-bin.zip Maven artifact along with a
binary shim in %ChocolateyInstall%\bin which lets you run AsciidoctorJ
from the command line.

  C:\> choco install asciidoctorj
  C:\> where asciidoctorj
  C:\ProgramData\chocolatey\bin\asciidoctorj.exe
  C:\> asciidoctorj -b pdf README.adoc
