= Examples

Here you will find simple but complete examples of how to convert documents using the different configuration options available.
The examples cover the main scenarios, but you can mix and match usage of instances, builders and maps freely to suite yous needs.

== Setting attributes and options as Map collections

[source,java]
----
Asciidoctor asciidoctor = Asciidoctor.Factory.create(); // <.>

Map<String, Object> attributes = AttributesBuilder.
                                   .attributes()
                                   .backend("docbook")
                                   .icons("font")
                                   .asMap();  // <.>

Map<String, Object> options = OptionsBuilder
                                .options()
                                .inPlace(true)
                                .attributes(attributes) // <.>
                                .asMap(); // <.>

String outfile = asciidoctor.convertFile(new File("sample.adoc"), options); // <.>
----
<.> Create `Asciidoctor` instance.
<.> Defines attributes using builder fluent API and retrieves them as `Map`.
<.> Registers the attributes map as `attributes`.
<.> Converts options to `java.util.Map` instance.

== Setting attributes and options as instances

[source,java]
----
Asciidoctor asciidoctor = Asciidoctor.Factory.create(); // <.>

Attributes attributes = AttributesBuilder.
                          .attributes()
                          .backend("docbook")
                          .icons("font")
                          .get(); // <.>

Options options = OptionsBuilder
                    .options()
                    .inPlace(true)
                    .attributes(attributes)
                    .get(); // <.>

String outfile = asciidoctor.convertFile(new File("sample.adoc"), options); // <.>
----
<.> Create `Asciidoctor` instance.
<.> Defines the attributes as an `Attributes` class instead of `java.util.Map` by calling `get()`.
<.> Defines the options as an `Options` class instead of `java.util.Map` by calling `get()`.
<.> Converts the document passing `Options` instance.

TIP: All methods used to convert content are overloaded with `OptionsBuilder` parameter.
It is no longer required to call `get` nor `asMap` methods.

WARNING: The `icons` attribute requires a `String` to set the value used to "draw" icons.
At this time, you can use two constants `org.asciidoctor.Attributes.IMAGE_ICONS` for using the same approach as AsciiDoc, that is using `img` tags, or `org.asciidoctor.Attributes.FONT_ICONS` for using icons from {url-font-awesome}[Font Awesome^].

== Setting attributes and options as builders

[source,java]
----
Asciidoctor asciidoctor = Asciidoctor.Factory.create(); // <.>

AttributesBuilder attributes = AttributesBuilder.
                                 .attributes()
                                 .backend("docbook")
                                 .icons("font"); // <.>

OptionsBuilder options = OptionsBuilder
                           .options()
                           .inPlace(true)
                           .attributes(attributes); // <.>

String outfile = asciidoctor.convertFile(new File("sample.adoc"), options); // <.>
----
<.> Create `Asciidoctor` instance.
<.> Defines the attributes as an `AttributesBuilder` by not using `get()` or `asMap().
<.> Defines the options as an `OptionsBuilder` by not using `get()` or `asMap().
<.> Converts the document passing `OptionsBuilder` instance.