= Extension Migration: 2.0.x to 3.0.x

Between 2.x and 3.0.x there are some changes that may affect existing extensions.
This guide will illustrate the changes.

== Preprocessor Extensions

In AsciidoctorJ 1.x and 2.x a Preprocessor could not return anything from its process() method.
This deviated from the API offered by Asciidoctor itself which allows to replace the original Reader.
Certain use cases were very hard or even impossible to achieve.

Therefore the signature of the method `Preprocessor.process()` was changed so that it now may return a new Reader.
This causes all existing Preprocessor implementation to fail compilation.
The fix for this is very simple: It is sufficient to change the method to return `null` or the given reader.

Let's assume that a Preprocessor originally looks like this:

[source,java]
----
public class ChangeAttributeValuePreprocessor extends Preprocessor {

	public ChangeAttributeValuePreprocessor(Map<String, Object> config) {
		super(config);
	}

	@Override
	public void process(Document document, PreprocessorReader reader) {
		document.getAttributes().put("myattribute", "myvalue");
	}
}
----

To make this Preprocessor compile and run with AsciidoctorJ 3.x it has to be changed like this

[source,java]
----
public class ChangeAttributeValuePreprocessor extends Preprocessor {

	public ChangeAttributeValuePreprocessor(Map<String, Object> config) {
		super(config);
	}

	@Override
	public Reader process(Document document, PreprocessorReader reader) { // <1>
		document.getAttributes().put("myattribute", "myvalue");
		return reader;                                                    // <2>
	}
}
----
<1> Change the method signature to return a `Reader` instead of `void`.
<2> Directly return the passed Reader.

== Inline Macro Extensions

The API that inline macro extensions had the return type `java.lang.Object`, while `org.asciidoctor.ast.PhraseNode` is actually expected.
Additionally, the parent node passed to the process method is guaranteed to be a `org.asciidoctor.ast.StructuralNode`, while the previous API offered the supertype `org.asciidoctor.ast.ContentNode`.
This is corrected in AsciidoctorJ 3.x making it clearer for extension implementors what types to expect and what types to return.

Let's assume that an InlineMacro originally looks like this for AsciidoctorJ 2.x:

[source,java]
----
public class KeyboardInlineMacroProcessor extends InlineMacroProcessor {
     @Override
     public Object process(ContentNode parent, String target, Map<String, Object> attributes) {
         Map<String, Object> attrs = new HashMap<>();
         attrs.put("keys", Arrays.asList("Ctrl", target));
         return createPhraseNode(parent, "kbd", (String) null, attrs);
    }
}
----

The only change that is necessary is to change the method declaration of the process method:
Change the return type to `org.asciidoctor.ast.PhraseNode` and the type of the first parameter to `org.asciidoctor.ast.StructuralNode`.

[source,java]
----
public class KeyboardInlineMacroProcessor extends InlineMacroProcessor {
     @Override
     public PhraseNode process(StructuralNode parent, String target, Map<String, Object> attributes) {
         Map<String, Object> attrs = new HashMap<>();
         attrs.put("keys", Arrays.asList("Ctrl", target));
         return createPhraseNode(parent, "kbd", (String) null, attrs);
    }
}
----

This change mostly makes it clearer for new extensions what they have to return and what they can expect.
